version: '3.8'

services:
  library-api:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "apk add git && 
             git clone https://github.com/artisMocans/library-api.git . && 
             npm install && 
             npm run dev"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/library
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: always

  cypress:
    image: cypress/included:13.6.1
    depends_on:
      - library-api
    environment:
      - CYPRESS_baseUrl=http://library-api:3000
    working_dir: /e2e
    volumes:
      - ./:/e2e
    command: >
      bash -c "npm install && npx cypress run"